// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beacon_block.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBlockBeaconByHeightRequest struct {
	Specific             bool     `protobuf:"varint,1,opt,name=Specific,proto3" json:"Specific,omitempty"`
	FromHeight           uint64   `protobuf:"varint,2,opt,name=FromHeight,proto3" json:"FromHeight,omitempty"`
	ToHeight             uint64   `protobuf:"varint,3,opt,name=ToHeight,proto3" json:"ToHeight,omitempty"`
	Heights              []uint64 `protobuf:"varint,4,rep,packed,name=Heights,proto3" json:"Heights,omitempty"`
	FromPool             bool     `protobuf:"varint,5,opt,name=FromPool,proto3" json:"FromPool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHeightRequest) Reset()         { *m = GetBlockBeaconByHeightRequest{} }
func (m *GetBlockBeaconByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHeightRequest) ProtoMessage()    {}
func (*GetBlockBeaconByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51e1cf297caacb65, []int{0}
}

func (m *GetBlockBeaconByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHeightRequest.Merge(m, src)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Size(m)
}
func (m *GetBlockBeaconByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHeightRequest proto.InternalMessageInfo

func (m *GetBlockBeaconByHeightRequest) GetSpecific() bool {
	if m != nil {
		return m.Specific
	}
	return false
}

func (m *GetBlockBeaconByHeightRequest) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GetBlockBeaconByHeightRequest) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GetBlockBeaconByHeightRequest) GetHeights() []uint64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *GetBlockBeaconByHeightRequest) GetFromPool() bool {
	if m != nil {
		return m.FromPool
	}
	return false
}

type GetBlockBeaconByHeightResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHeightResponse) Reset()         { *m = GetBlockBeaconByHeightResponse{} }
func (m *GetBlockBeaconByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHeightResponse) ProtoMessage()    {}
func (*GetBlockBeaconByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51e1cf297caacb65, []int{1}
}

func (m *GetBlockBeaconByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHeightResponse.Merge(m, src)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Size(m)
}
func (m *GetBlockBeaconByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHeightResponse proto.InternalMessageInfo

func (m *GetBlockBeaconByHeightResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockBeaconByHashRequest struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHashRequest) Reset()         { *m = GetBlockBeaconByHashRequest{} }
func (m *GetBlockBeaconByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHashRequest) ProtoMessage()    {}
func (*GetBlockBeaconByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51e1cf297caacb65, []int{2}
}

func (m *GetBlockBeaconByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHashRequest.Merge(m, src)
}
func (m *GetBlockBeaconByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Size(m)
}
func (m *GetBlockBeaconByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHashRequest proto.InternalMessageInfo

func (m *GetBlockBeaconByHashRequest) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type GetBlockBeaconByHashResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHashResponse) Reset()         { *m = GetBlockBeaconByHashResponse{} }
func (m *GetBlockBeaconByHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHashResponse) ProtoMessage()    {}
func (*GetBlockBeaconByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51e1cf297caacb65, []int{3}
}

func (m *GetBlockBeaconByHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHashResponse.Merge(m, src)
}
func (m *GetBlockBeaconByHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Size(m)
}
func (m *GetBlockBeaconByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHashResponse proto.InternalMessageInfo

func (m *GetBlockBeaconByHashResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBlockBeaconByHeightRequest)(nil), "msg.GetBlockBeaconByHeightRequest")
	proto.RegisterType((*GetBlockBeaconByHeightResponse)(nil), "msg.GetBlockBeaconByHeightResponse")
	proto.RegisterType((*GetBlockBeaconByHashRequest)(nil), "msg.GetBlockBeaconByHashRequest")
	proto.RegisterType((*GetBlockBeaconByHashResponse)(nil), "msg.GetBlockBeaconByHashResponse")
}

func init() { proto.RegisterFile("beacon_block.proto", fileDescriptor_51e1cf297caacb65) }

var fileDescriptor_51e1cf297caacb65 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x4a, 0x4d, 0x4c,
	0xce, 0xcf, 0x8b, 0x4f, 0xca, 0xc9, 0x4f, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xce, 0x2d, 0x4e, 0x57, 0x5a, 0xcb, 0xc8, 0x25, 0xeb, 0x9e, 0x5a, 0xe2, 0x04, 0x12, 0x77, 0x02,
	0xab, 0x71, 0xaa, 0xf4, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x92, 0xe2, 0xe2, 0x08, 0x2e, 0x48, 0x4d, 0xce, 0x4c, 0xcb, 0x4c, 0x96, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x08, 0x82, 0xf3, 0x85, 0xe4, 0xb8, 0xb8, 0xdc, 0x8a, 0xf2, 0x73, 0x21, 0x1a, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x58, 0x82, 0x90, 0x44, 0x40, 0x7a, 0x43, 0xf2, 0xa1, 0xb2, 0xcc, 0x60,
	0x59, 0x38, 0x5f, 0x48, 0x82, 0x8b, 0x1d, 0xc2, 0x2a, 0x96, 0x60, 0x51, 0x60, 0xd6, 0x60, 0x09,
	0x82, 0x71, 0x41, 0xba, 0x40, 0x66, 0x04, 0xe4, 0xe7, 0xe7, 0x48, 0xb0, 0x42, 0x6c, 0x84, 0xf1,
	0x95, 0x4c, 0xb8, 0xe4, 0x70, 0x39, 0xb7, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88, 0x8b,
	0xc5, 0x25, 0xb1, 0x24, 0x11, 0xec, 0x56, 0x9e, 0x20, 0x30, 0x5b, 0xc9, 0x94, 0x4b, 0x1a, 0x43,
	0x57, 0x62, 0x71, 0x06, 0xcc, 0x8b, 0x62, 0x5c, 0x6c, 0x20, 0x6e, 0x6a, 0xb1, 0x04, 0xa3, 0x02,
	0xb3, 0x06, 0x4f, 0x10, 0x94, 0xa7, 0x64, 0xc4, 0x25, 0x83, 0x5d, 0x1b, 0x6e, 0xab, 0x9c, 0x58,
	0xa3, 0x40, 0xe1, 0x9a, 0xc4, 0x06, 0x0e, 0x63, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x22, 0xd7, 0x32, 0x79, 0x01, 0x00, 0x00,
}
