// Code generated by protoc-gen-go. DO NOT EDIT.
// source: highway.proto

package process

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("highway.proto", fileDescriptor_a48762df9e8cc53a) }

var fileDescriptor_a48762df9e8cc53a = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x9f, 0xe5, 0xe1, 0xe5, 0x24, 0x2a, 0xd5, 0xb4, 0x08, 0x65, 0xa1, 0x2d, 0x6f, 0x5b,
	0x06, 0x98, 0x58, 0xc3, 0x40, 0xe7, 0x76, 0xab, 0x84, 0x8a, 0x63, 0x4e, 0xb1, 0x05, 0xd4, 0xc1,
	0x67, 0x40, 0xfd, 0x48, 0x7c, 0x4b, 0xe4, 0x34, 0xb6, 0xea, 0x36, 0x4d, 0x47, 0x9f, 0x7f, 0xf7,
	0xff, 0xf9, 0x72, 0x81, 0x13, 0xa9, 0x0a, 0xf9, 0xc3, 0x97, 0x69, 0x69, 0xb4, 0xd5, 0x49, 0xc7,
	0x60, 0xa1, 0xc8, 0xa2, 0xa9, 0xcf, 0x5d, 0x92, 0xdc, 0xbc, 0xce, 0xf3, 0x77, 0x2d, 0xde, 0xea,
	0x12, 0xcb, 0x91, 0x0b, 0xbd, 0x88, 0x6a, 0x5d, 0x61, 0x34, 0xd1, 0xbc, 0x82, 0x57, 0xa5, 0xbb,
	0xdf, 0xff, 0xd0, 0x19, 0xaf, 0xb2, 0xa7, 0x68, 0xbe, 0x95, 0x40, 0xf6, 0x00, 0x47, 0x93, 0x3a,
	0x9e, 0xf5, 0xd2, 0x0f, 0x2a, 0x52, 0x7f, 0x9c, 0xe0, 0xe7, 0x17, 0x92, 0x4d, 0xfa, 0x1b, 0x55,
	0x2a, 0xf5, 0x82, 0x70, 0xf4, 0x8f, 0xbd, 0x40, 0xff, 0x09, 0x6d, 0xe6, 0x94, 0x53, 0x27, 0xc9,
	0x96, 0x63, 0x54, 0x85, 0xb4, 0x6c, 0x58, 0x75, 0x34, 0xde, 0xf9, 0xd0, 0x51, 0x1b, 0x12, 0x0c,
	0x33, 0x38, 0xdd, 0x44, 0x38, 0x49, 0x76, 0xd1, 0xd8, 0xcc, 0x49, 0xfa, 0xf4, 0xc1, 0x6e, 0x20,
	0x64, 0x0b, 0x38, 0xf3, 0x40, 0x56, 0x7d, 0xbc, 0xf0, 0xfc, 0xf8, 0x6d, 0xf1, 0xa5, 0x37, 0x5c,
	0xb6, 0x32, 0x41, 0xf2, 0x0c, 0xbd, 0x2d, 0xc6, 0x4d, 0x30, 0x68, 0x6e, 0x5f, 0x1b, 0x61, 0xd8,
	0x42, 0x84, 0x78, 0x0d, 0x89, 0x27, 0x1e, 0xdd, 0xb2, 0xe3, 0x35, 0xdc, 0x44, 0x11, 0xdb, 0x80,
	0x57, 0xdd, 0xee, 0xe5, 0x82, 0x50, 0xc1, 0x79, 0x23, 0xe7, 0x66, 0xba, 0xda, 0x1d, 0xb3, 0x36,
	0xd7, 0xf5, 0x1e, 0xca, 0xab, 0xb2, 0xe3, 0xd9, 0x61, 0x69, 0xb4, 0x40, 0xa2, 0xfc, 0xa0, 0xfa,
	0x7b, 0xef, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xe1, 0x6c, 0x01, 0x18, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HighwayServiceClient is the client API for HighwayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HighwayServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetBlockShardByHeight(ctx context.Context, in *GetBlockShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardByHeightResponse, error)
	GetBlockShardByHash(ctx context.Context, in *GetBlockShardByHashRequest, opts ...grpc.CallOption) (*GetBlockShardByHashResponse, error)
	GetBlockBeaconByHeight(ctx context.Context, in *GetBlockBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHeightResponse, error)
	GetBlockBeaconByHash(ctx context.Context, in *GetBlockBeaconByHashRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHashResponse, error)
	GetBlockCrossShardByHeight(ctx context.Context, in *GetBlockCrossShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHeightResponse, error)
	GetBlockCrossShardByHash(ctx context.Context, in *GetBlockCrossShardByHashRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHashResponse, error)
}

type highwayServiceClient struct {
	cc *grpc.ClientConn
}

func NewHighwayServiceClient(cc *grpc.ClientConn) HighwayServiceClient {
	return &highwayServiceClient{cc}
}

func (c *highwayServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockShardByHeight(ctx context.Context, in *GetBlockShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardByHeightResponse, error) {
	out := new(GetBlockShardByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockShardByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockShardByHash(ctx context.Context, in *GetBlockShardByHashRequest, opts ...grpc.CallOption) (*GetBlockShardByHashResponse, error) {
	out := new(GetBlockShardByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockShardByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockBeaconByHeight(ctx context.Context, in *GetBlockBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHeightResponse, error) {
	out := new(GetBlockBeaconByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockBeaconByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockBeaconByHash(ctx context.Context, in *GetBlockBeaconByHashRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHashResponse, error) {
	out := new(GetBlockBeaconByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockBeaconByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockCrossShardByHeight(ctx context.Context, in *GetBlockCrossShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHeightResponse, error) {
	out := new(GetBlockCrossShardByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockCrossShardByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockCrossShardByHash(ctx context.Context, in *GetBlockCrossShardByHashRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHashResponse, error) {
	out := new(GetBlockCrossShardByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockCrossShardByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HighwayServiceServer is the server API for HighwayService service.
type HighwayServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetBlockShardByHeight(context.Context, *GetBlockShardByHeightRequest) (*GetBlockShardByHeightResponse, error)
	GetBlockShardByHash(context.Context, *GetBlockShardByHashRequest) (*GetBlockShardByHashResponse, error)
	GetBlockBeaconByHeight(context.Context, *GetBlockBeaconByHeightRequest) (*GetBlockBeaconByHeightResponse, error)
	GetBlockBeaconByHash(context.Context, *GetBlockBeaconByHashRequest) (*GetBlockBeaconByHashResponse, error)
	GetBlockCrossShardByHeight(context.Context, *GetBlockCrossShardByHeightRequest) (*GetBlockCrossShardByHeightResponse, error)
	GetBlockCrossShardByHash(context.Context, *GetBlockCrossShardByHashRequest) (*GetBlockCrossShardByHashResponse, error)
}

// UnimplementedHighwayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHighwayServiceServer struct {
}

func (*UnimplementedHighwayServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockShardByHeight(ctx context.Context, req *GetBlockShardByHeightRequest) (*GetBlockShardByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockShardByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockShardByHash(ctx context.Context, req *GetBlockShardByHashRequest) (*GetBlockShardByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockShardByHash not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockBeaconByHeight(ctx context.Context, req *GetBlockBeaconByHeightRequest) (*GetBlockBeaconByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockBeaconByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockBeaconByHash(ctx context.Context, req *GetBlockBeaconByHashRequest) (*GetBlockBeaconByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockBeaconByHash not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockCrossShardByHeight(ctx context.Context, req *GetBlockCrossShardByHeightRequest) (*GetBlockCrossShardByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockCrossShardByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockCrossShardByHash(ctx context.Context, req *GetBlockCrossShardByHashRequest) (*GetBlockCrossShardByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockCrossShardByHash not implemented")
}

func RegisterHighwayServiceServer(s *grpc.Server, srv HighwayServiceServer) {
	s.RegisterService(&_HighwayService_serviceDesc, srv)
}

func _HighwayService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockShardByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockShardByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockShardByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockShardByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockShardByHeight(ctx, req.(*GetBlockShardByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockShardByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockShardByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockShardByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockShardByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockShardByHash(ctx, req.(*GetBlockShardByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockBeaconByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockBeaconByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockBeaconByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockBeaconByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockBeaconByHeight(ctx, req.(*GetBlockBeaconByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockBeaconByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockBeaconByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockBeaconByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockBeaconByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockBeaconByHash(ctx, req.(*GetBlockBeaconByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockCrossShardByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockCrossShardByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockCrossShardByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHeight(ctx, req.(*GetBlockCrossShardByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockCrossShardByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockCrossShardByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockCrossShardByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHash(ctx, req.(*GetBlockCrossShardByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HighwayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HighwayService",
	HandlerType: (*HighwayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _HighwayService_Register_Handler,
		},
		{
			MethodName: "GetBlockShardByHeight",
			Handler:    _HighwayService_GetBlockShardByHeight_Handler,
		},
		{
			MethodName: "GetBlockShardByHash",
			Handler:    _HighwayService_GetBlockShardByHash_Handler,
		},
		{
			MethodName: "GetBlockBeaconByHeight",
			Handler:    _HighwayService_GetBlockBeaconByHeight_Handler,
		},
		{
			MethodName: "GetBlockBeaconByHash",
			Handler:    _HighwayService_GetBlockBeaconByHash_Handler,
		},
		{
			MethodName: "GetBlockCrossShardByHeight",
			Handler:    _HighwayService_GetBlockCrossShardByHeight_Handler,
		},
		{
			MethodName: "GetBlockCrossShardByHash",
			Handler:    _HighwayService_GetBlockCrossShardByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "highway.proto",
}
